version: '3'

services:
  web:
    container_name: events_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - database
      - test_database
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      FLASK_ENV: development
      DB_HOST: database
      DB_TEST_HOST: test_database
      PYTHONPATH: /app/src

  database:
    container_name: database
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

  test_database:
    container_name: test_database
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_database
    ports:
      - 5433:5432