version: '3'

services:
  web:
    container_name: events_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - database
      - test_database
    working_dir: /app
    volumes:
      - ./:/app
      - ./public/images:/app/public/images
    environment:
      FLASK_ENV: development
      DB_HOST: database
      DB_TEST_HOST: test_database
      PYTHONPATH: /app/src

  database:
    container_name: database
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

  test_database:
    container_name: test_database
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_database
    ports:
      - 5433:5432

  # localstack:
  #   image: localstack/localstack
  #   environment:
  #     SERVICES: s3
  #     DATA_DIR: /tmp/localstack/data
  #     # AWS
  #     AWS_ACCESS_KEY_ID: 1234
  #     AWS_SECRET_ACCESS_KEY: 1234
  #     AWS_DEFAULT_REGION: us-east-1
  #     AWS_DEFAULT_OUTPUT: json
  #   ports:
  #     - "4566-4576:4566-4576"
  #   volumes:
  #     - ./localstack/data:/tmp/localstack/data

  # aws_cli_config:
  #   container_name: aws_cli_config
  #   image: amazon/aws-cli
  #   entrypoint: /bin/sh -c
  #   depends_on:
  #     - localstack
  #   command: >
  #     '
  #         echo "##### STARTED - WAIT 20 SECONDS #####"
  #         sleep 20

  #         echo "########### Creating profile ###########"
  #         aws configure set aws_access_key_id default_access_key --profile=localstack
  #         aws configure set aws_secret_access_key default_secret_key --profile=localstack
  #         aws configure set region us-east-1 --profile=localstack

  #         echo "########### Creating BUCKET ###########"
  #         aws --endpoint-url=http://localstack:4566 s3 mb s3://backend-events-time-images --profile=localstack
  #         aws --endpoint-url=http://localstack:4566 s3api put-bucket-acl --bucket backend-events-time-images --acl public-read --profile=localstack
  #     '